# https://toml.io/en/
name = "bali"
version = "3.0.0"
crates = [
    "cmd/bali",     # crates
    "cmd/peassets",
]
description = "Bali - Minimalist Golang build and packaging tool"

dirs = [
    "cmd/bali",     # targets
    "cmd/peassets",
]

[[files]]
path = "LICENSE"
destination = "share"
rename = "BALI-COPYRIGHT.txt"

[[include]]
path = "LICENSE"
destination = "share"
rename = "BALI-COPYRIGHT.txt"
permissions = "0664"
