# https://toml.io/en/
name = "bali"
version = "2.2.0"
dirs = [
    "cmd/bali", # dirs
    "cmd/peassets",
]
destination = "Bali - Minimalist Golang build and packaging tool"

[[files]]
path = "LICENSE"
destination = "share"
newname = "LICENSE.bali"
norename = true
