# https://toml.io/en/
name = "bali"
version = "1.2.12"
dirs = [
    "cmd/bali", # dirs
]
destination = "Bali - Minimalist Golang build and packaging tool"

[[files]]
path = "LICENSE"
destination = "share"
newname = "LICENSE.bali"
norename = true
