# https://toml.io/en/
name = "bali"
version = "3.0.0"
dirs = [
    "cmd/bali",     # dirs
    "cmd/peassets",
]
description = "Bali - Minimalist Golang build and packaging tool"

[[files]]
path = "LICENSE"
destination = "share"
newname = "LICENSE.bali"
norename = true
