name: CI
on:
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "LICENSE"
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            bootstrap_script: ./script/bootstrap.sh
          - platform: macos-latest
            bootstrap_script: ./script/bootstrap.sh
          - platform: windows-latest
            bootstrap_script: script/bootstrap.bat
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Bootstrap Bali
        run: ${{ matrix.bootstrap_script }}
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          file: out/*
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
